export const mainItemsData = [
  {
    itemId: 0,
    itemsTag: ['같이 사요 🛍️', '배달비 🛵'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '마포구청역 근처 같이 치킨시켜 드실 분?',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '12,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 5,
  },
  {
    itemId: 1,
    itemsTag: ['같이 사요 🛍️', '식품 🍞'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: `수박 같이 사서 나누실 분!
      어떻게 나눌지 같이 고민해봐요.`,
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 10,
    itemsCurrentParticipants: 4,
    itemsPrice: '같이 정해요',
    itemsDeadline: '07/07',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 4,
  },
  {
    itemId: 2,
    itemsTag: ['너무 많아요 🤝', '홈메이드 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 5,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 8,
  },
  {
    itemId: 3,
    itemsTag: ['같이 나눠요 🤝', '홈메이드 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
  },
  {
    itemId: 4,
    itemsTag: ['너무 많아요 🤝', '같이 나눠요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
  },
  {
    itemId: 5,
    itemsTag: ['같이 주문해요 🤝', '홈메이드 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 4,
  },
  {
    itemId: 6,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠', '같이 나눠요 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 2,
  },
  {
    itemId: 7,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 0,
  },
  {
    itemId: 8,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 2,
  },
  {
    itemId: 9,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 5,
  },
  {
    itemId: 10,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '망원동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 5,
  },
  {
    itemId: 11,
    itemsTag: ['너무 많아요 🤝', '같이 주문해요 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '망원동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '06/30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 7,
  },
];

export const options = [
  { value: '성산동', label: '성산동' },
  { value: '망원동', label: '망원동' },
  { value: '합정동', label: '합정동' },
];
