export const mainItemsData = [
  {
    itemId: 0,
    itemsTag: ['배달 🛵'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '카페 마마스 같이 시키실 분? 마포중앙도서관 근처 ',
    itemsText: `샐러드랑 청포도주스 먹고싶은데 동네에 카페 마마스가 없어서 배민으로 주문하려고 합니다. 
    마포중앙도서관 앞에서 만나 같이 주문하고 
    배달비 나눠내요~`,
    itemsConfidence: true,
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '4,200',
    itemsDeadline: '08.23',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃001',

    // itemsCategory,
    // itemsText,
    // itemsLink,
    // itemsisHomemade,
    // itemsDate,
  },
  {
    itemId: 1,
    itemsTag: ['OTT 📺'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: `넷플릭스 공동 구독 3분`,
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '12,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃002',
  },
  {
    itemId: 2,
    itemsTag: ['식품 🍎'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '농수산물 같이 사서 나눠먹어요!',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 5,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃003',
  },
  {
    itemId: 3,
    itemsTag: ['의류 👕'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '요가복 할인 중인데 같이 사서 택배비 나누실 분?',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '3,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃004',
  },
  {
    itemId: 4,
    itemsTag: ['의류 👕'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 5,
    itemUserName: '동네이웃005',
  },
  {
    itemId: 5,
    itemsTag: ['생활용품 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '똑똑 섬유유연제 필요하신분? 하나 가져가세요~',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '나눔',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃006',
  },
  {
    itemId: 6,
    itemsTag: ['식품 🍎', '홈메이드 🧡'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬이랑 과자 물물교환 원해요.',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '물물교환',
    itemsDeadline: '08.30',
    isHeartEmpty: false,

    itemsHeartCount: 0,
    itemUserName: '동네이웃007',
  },
  {
    itemId: 7,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '홈플러스에서 만나 같이 장봐요!',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    itemsHeartCount: 0,
    itemUserName: '동네이웃008',
  },
  // {
  //   itemId: 8,
  //   itemsTag: ['장보기 친구 🤝'],
  //   itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
  //   itemsHeadText: '집반찬 물물교환해요',
  //   itemsTownLocation: '성산동',
  //   itemsLimitParticipants: 2,
  //   itemsCurrentParticipants: 1,
  //   itemsPrice: '6,000',
  //   itemsDeadline: '08.30',
  //   isHeartEmpty: false,
  //
  //   itemsHeartCount: 2,
  // },
  // {
  //   itemId: 9,
  //   itemsTag: ['장보기 친구 🤝'],
  //   itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
  //   itemsHeadText: '집반찬 물물교환해요',
  //   itemsTownLocation: '성산동',
  //   itemsLimitParticipants: 2,
  //   itemsCurrentParticipants: 1,
  //   itemsPrice: '6,000',
  //   itemsDeadline: '08.30',
  //   isHeartEmpty: false,
  //
  //   itemsHeartCount: 5,
  // },
  // {
  //   itemId: 10,
  //   itemsTag: ['장보기 친구 🤝'],
  //   itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
  //   itemsHeadText: '집반찬 물물교환해요',
  //   itemsTownLocation: '망원동',
  //   itemsLimitParticipants: 2,
  //   itemsCurrentParticipants: 1,
  //   itemsPrice: '6,000',
  //   itemsDeadline: '08.30',
  //   isHeartEmpty: false,
  //
  //   itemsHeartCount: 5,
  // },
  // {
  //   itemId: 11,
  //   itemsTag: ['장보기 친구 🤝'],
  //   itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
  //   itemsHeadText: '집반찬 물물교환해요',
  //   itemsTownLocation: '망원동',
  //   itemsLimitParticipants: 2,
  //   itemsCurrentParticipants: 1,
  //   itemsPrice: '6,000',
  //   itemsDeadline: '08.30',
  //   isHeartEmpty: false,
  //
  //   itemsHeartCount: 7,
  // },
];
