export const mainItemsData = [
  {
    itemId: 0,
    itemsTag: ['배달 🛵'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '카페 마마스 같이 시키실 분? 마포중앙도서관 근처 ',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '12,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
    // itemsCategory,
    // itemsText,
    // itemsLink,
    // itemsisHomemade,
    // itemsDate,
  },
  {
    itemId: 1,
    itemsTag: ['OTT 📺'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: `수박 같이 사서 나누실 분!
      어떻게 나눌지 같이 고민해봐요.`,
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 10,
    itemsCurrentParticipants: 4,
    itemsPrice: '같이 정해요',
    itemsDeadline: '07.07',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 4,
  },
  {
    itemId: 2,
    itemsTag: ['식품 🍎'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 5,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 8,
  },
  {
    itemId: 3,
    itemsTag: ['의류 👕'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 3,
    itemsCurrentParticipants: 1,
    itemsPrice: '같이 정해요',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: true,
    itemsHeartCount: 5,
  },
  {
    itemId: 4,
    itemsTag: ['의류 👕'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
  },
  {
    itemId: 5,
    itemsTag: ['생활용품 🏠'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 4,
  },
  {
    itemId: 6,
    itemsTag: ['식품 🍎', '홈메이드 🧡'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 2,
  },
  {
    itemId: 7,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '합정동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 0,
  },
  {
    itemId: 8,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 2,
  },
  {
    itemId: 9,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '성산동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
  },
  {
    itemId: 10,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '망원동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 5,
  },
  {
    itemId: 11,
    itemsTag: ['장보기 친구 🤝'],
    itemsImg: `${process.env.PUBLIC_URL}/assets/images/main_thumbnail.png`,
    itemsHeadText: '집반찬 물물교환해요',
    itemsTownLocation: '망원동',
    itemsLimitParticipants: 2,
    itemsCurrentParticipants: 1,
    itemsPrice: '6,000',
    itemsDeadline: '08.30',
    isHeartEmpty: false,
    isLock: false,
    itemsHeartCount: 7,
  },
];
